version: "3"  

tasks:  
  default:
    cmds:  
      - task: generate  
  
  pre-configuration-scylladb:
    desc: "Create user for scyllaDB"  
    cmds:
      - echo "Waiting 30 seconds for ScyllaDB to start..."
      - sleep 30
      
      - sudo docker cp init_auth.cql scylla_node:/init_auth.cql
      
      - echo "Applying ScyllaDB configuration from static file..."
      - sudo docker exec scylla_node cqlsh -u cassandra -p cassandra -f /init_auth.cql
      
      - sudo docker exec -u 0 scylla_node rm /init_auth.cql
      
      - echo "ScyllaDB successfully configured! 🎉"
    silent: false

  generate-user-info-proto: 
    desc: "Generate code from proto user_info file"  
    cmds:
      - protoc -I proto proto/user_info/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  generate-file-storage-proto:
    desc: "Generate code from proto file_storage file"
    cmds:
      - protoc -I proto proto/file_storage/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  
  generate-permissions-proto:
    desc: "Generate code from proto permissions file"
    cmds:
      - protoc -I proto proto/permissions/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  raise-sso:
    cmds:
      - sudo docker compose --env-file ./sso.local.env -f containers/redis.docker-compose.yaml up -d
      - sudo docker compose --env-file ./sso.local.env -f containers/postgres.docker-compose.yaml up -d
      - sleep 3
      - go run cmd/migrator/main.go -env ./sso.local.env -db postgresql
      - sleep 3
      - go run cmd/sso/main.go - env local

  raise-sso-prod:
    cmds:
      - sudo docker compose --env-file ./sso.prod.env -f containers/postgres.docker-compose.yaml up -d
      - sleep 3
      - go run cmd/migrator/main.go -env prod -db postgresql
      - sleep 3
      - go run cmd/sso/main.go -env prod

  raise-messenger:
    cmds:
      - sudo docker compose --env-file ./messenger.local.env -f containers/scylla.docker-compose.yaml up -d
      - sleep 1
      - task pre-configuration-scylladb
      - sleep 3
      - go run cmd/migrator/main.go -env ./messenger.local.env -db scylladb
      - sleep 3
      - go run cmd/messenger/main.go -env local

  raise-messenger-prod:
    cmds:
      - sudo docker compose --env-file ./messenger.prod.env -f containers/scylla.docker-compose.yaml up -d
      - sleep 1
      - task pre-configuration-scylladb
      - sleep 3
      - go run cmd/migrator/main.go -env ./messenger.prod.env -db scylladb
      - sleep 3
      - go run cmd/messenger/main.go -env prod

  raise-file-storage:
    cmds:
      - sudo docker compose --env-file ./minIO.local.env -f containers/minIO.docker-compose.yaml up -d
      - sleep 3
      - go run cmd/file_storage/main.go -env local
      
  
  raise-file-storage-prod:
    cmds:
      - sudo docker compose --env-file ./minIO.prod.env -f containers/minIO.docker-compose.yaml up -d
      - sleep 3
      - go run cmd/file_storage/main.go -env prod

  raise-sfu:
    cmds:
      - sudo docker compose -f containers/livekit.docker-compose.yaml up -d
      - sleep 3
      - go run cmd/sfu/main.go -env local

  raise-sfu-prod:
    cmds:
      - sudo docker compose -f containers/livekit.docker-compose.yaml up -d
      - sleep 3
      - go run cmd/sfu/main.go -env prod
  
  
