gin:
  - name: messenger
    port: 8082
    enabled: true
    sw:
      enabled: true
    docs:
      enabled: true
    prom:
      enabled: true
    middleware:
      logging:
        enabled: true
      prom:
        enabled: true
      meta:
        enabled: true
    timeout:
      enabled: true
      timeoutMs: 5000
